MODULE PARAMETERS
! MODULE WITH THE PARAMETERS NEEDED IN THE SIMULATION
! PEDRO OJEDA,  07/MAY/2011

IMPLICIT NONE
   INTEGER, PARAMETER  :: NUM_RES=1000                     !NUMBER OF AMINOACIDS IN EACH SEQUENCE
   INTEGER, PARAMETER  :: DP = SELECTED_REAL_KIND(12, 60)
   INTEGER, PARAMETER  :: TIME=90000                       !TIME OF SIMULATION
   INTEGER, SAVE       :: NSTEP
   INTEGER             :: CLASE(NUM_RES)                   !SEQUENCES OF AMINOACIDS
   INTEGER             :: I,J,K,L,M
   INTEGER, PARAMETER  :: SECU=1                           !THE NUMBER OF SEQUENCE                            
   REAL(DP),PARAMETER  :: PI=3.141592653589793_DP           !PI CONSTANT
   REAL(DP),PARAMETER  :: DT=0.0001_DP                      !TIME STEP
   REAL(DP)            :: DT2=DT*DT                        !TIME STEP SQUARED
   REAL(DP)            :: DTP5=0.5_DP*DT                    !TIME STEP HALFED
   REAL(DP),PARAMETER  :: KBT_CONST = 0.5_DP                !KB * T 
   REAL(DP)            :: EPS_CONST(4,4)                   !ARRAY FOR EPSILON
   REAL(DP)            :: SIGMA_CONST(NUM_RES,NUM_RES)     !ARRAY OF SIGMA
   REAL(DP),PARAMETER  :: R_CERO=3.8_DP                     !SPRING EQUILIBRIUM SEPARATION
   REAL(DP),PARAMETER  :: A_CONST=50.0_DP                   !SPRING CONSTANT
   REAL(DP)            :: POT_ENER                         !POTENTIAL ENERGY
   REAL(DP)            :: KIN_ENER                         !KINETIC ENERGY
   CHARACTER*1         :: AMINO(4)=(/'S','C','P','N'/)     !ALPHABET OF FOUR LETTERS        
   
   INTEGER,SAVE        :: O = 1, N = 1                     !INDICES FOR OLD AND NEW CONFIGURATIONS
   
   ! PARTICLE DATA (STRUCTURE OF ARRAYS)
   REAL(DP), SAVE :: COORX(NUM_RES)
   REAL(DP), SAVE :: COORY(NUM_RES)
   REAL(DP), SAVE :: COORZ(NUM_RES)
   
   REAL(DP), SAVE :: VELX(NUM_RES)
   REAL(DP), SAVE :: VELY(NUM_RES)
   REAL(DP), SAVE :: VELZ(NUM_RES)
   
   REAL(DP), SAVE :: GRADX(2,NUM_RES)
   REAL(DP), SAVE :: GRADY(2,NUM_RES)
   REAL(DP), SAVE :: GRADZ(2,NUM_RES)
   
   REAL(DP), SAVE :: MASS(NUM_RES)
   REAL(DP), SAVE :: CHARGE(NUM_RES)
   REAL(DP), SAVE :: INERTIA(NUM_RES)

END MODULE PARAMETERS

MODULE RNG_UTILS
  USE PARAMETERS
  IMPLICIT NONE
CONTAINS

  SUBROUTINE INIT_RANDOM_SEED()
    INTEGER :: i, n, clock
    INTEGER, ALLOCATABLE :: seed(:)

    CALL RANDOM_SEED(SIZE=n)
    ALLOCATE(seed(n))

    CALL SYSTEM_CLOCK(COUNT=clock)

    DO i = 1, n
       seed(i) = clock + 37*i
    END DO

    CALL RANDOM_SEED(PUT=seed)
    DEALLOCATE(seed)
  END SUBROUTINE INIT_RANDOM_SEED


  FUNCTION RANDN() RESULT(z)
    REAL(DP) :: z
    REAL(DP) :: u1, u2

    CALL RANDOM_NUMBER(u1)
    CALL RANDOM_NUMBER(u2)

    IF (u1 <= 1.0D-12) u1 = 1.0D-12

    z = SQRT(-2.0_DP*LOG(u1)) * COS(2.0_DP*PI*u2)
  END FUNCTION RANDN

END MODULE RNG_UTILS

PROGRAM MOLECULAR_DYNAMICS
! MAIN PROGRAM TO RUN THE MOLECULAR DYNAMICS
! PEDRO OJEDA,  07/MAY/2011

USE PARAMETERS
USE RNG_UTILS
INTEGER             :: P
INTEGER             :: TMP
REAL(DP)            :: ENER

CHARACTER*40 NAME4


!READ THE SEQUENCE
!IF(SECU.LT.10) THEN
!   WRITE(NAME4,"('../Data/sec_',i1,'.dat')")SECU
!ELSE
!   WRITE(NAME4,"('../Data/sec_',i2,'.dat')")SECU
!ENDIF
!OPEN(55,FILE=NAME4,STATUS='UNKNOWN')
DO P=1,NUM_RES
    !READ(55,*)	CLASE(P)
    CLASE(P) = 4
ENDDO
!CLOSE(55)


!ASSIGN THE VALUES FOR THE EPSILONS AND SIGMAS
        CALL SECUENCIAS

        CALL INITIALIZE

        !OPEN(88,FILE='../Data/min_0.dat',STATUS='UNKNOWN')
        !           DO P=1,NUM_RES
        !                READ(88,*) COORX(P),COORY(P),COORZ(P)
        !           ENDDO
        !CLOSE(88)

        CALL FORCES


        OPEN(88,FILE='KOORDINATEN_1T.xyz',STATUS='UNKNOWN')



!MAIN PART OF MOLECULAR DINAMICS
        N = 2
        DO NSTEP=1,10000

               CALL UPDATE_VEL_VERLET_COOR
               CALL FORCES
               CALL UPDATE_VEL_VERLET_VEL
               CALL KINETIC

               TMP = O
               O = N 
               N = TMP

               IF(MOD(NSTEP,1000).EQ.0) THEN 
                   WRITE(88,*) NUM_RES
                   WRITE(88,*) '  '
                   DO P=1,NUM_RES
                        WRITE(88,*) 'C', COORX(P), COORY(P),COORZ(P)
                   ENDDO
                   WRITE(6,*) POT_ENER, KIN_ENER, POT_ENER + KIN_ENER
               ENDIF

        ENDDO
        CLOSE(88)

END PROGRAM MOLECULAR_DYNAMICS



SUBROUTINE LENNARD_JONES 
! SUBROUTINE TO COMPUTE THE LENNARD-JONES POTENTIAL AND FORCE
! PEDRO OJEDA,  07/MAY/2011

USE PARAMETERS
REAL(DP)            :: FDUMMY1,FDUMMY2,FDUMMY4,FDUMMY5
REAL(DP)            :: FDUMMYD,FDUMMYE
REAL(DP)            :: FTERM
REAL(DP)            :: ENER1
REAL(DP)            :: DISX,DISY,DISZ,DISD

ENER1=0.0_DP

!VAN DER WAALS CONTRIBUTION
DO I=1,NUM_RES-2
     DO J=I+2,NUM_RES
        DISX=COORX(I)-COORX(J)                          
        DISY=COORY(I)-COORY(J)                          
        DISZ=COORZ(I)-COORZ(J)                           
        DISD=DISX*DISX + DISY*DISY + DISZ*DISZ        

        FDUMMY1=SIGMA_CONST(I,J)*SIGMA_CONST(I,J)/DISD
        K=CLASE(I)
        L=CLASE(J)
        FDUMMY2=FDUMMY1*FDUMMY1                             ! POWER 4
        FDUMMY4=FDUMMY2*FDUMMY1                             ! POWER 6
        FDUMMY5=FDUMMY4*FDUMMY4                             ! POWER 12
        FDUMMYD=1.0_DP/DISD                                 ! 1/DISTANCE_IJ^2
        FDUMMYE=FDUMMY5-FDUMMY4                             ! (SIGMA/R)^12 - (SIGMA/R)^6
        ENER1=ENER1+EPS_CONST(K,L)*FDUMMYE                  ! ENERGY = EPSILON*[(SIGMA/R)^12 - (SIGMA/R)^6 ]
        FTERM=(12.0_DP*FDUMMY5-6.0_DP*FDUMMY4)*FDUMMYD      ! FORCE = -DV/DR = [12*(SIGMA/R)^12 - 6*(SIGMA/R)^6 ]*(1/R^2)

        GRADX(N,I)=GRADX(N,I)+EPS_CONST(K,L)*FTERM*DISX   ! X COMPONENT OF THE GRADIENT
        GRADY(N,I)=GRADY(N,I)+EPS_CONST(K,L)*FTERM*DISY   ! Y COMPONENT OF THE GRADIENT
        GRADZ(N,I)=GRADZ(N,I)+EPS_CONST(K,L)*FTERM*DISZ   ! Z COMPONENT OF THE GRADIENT
        GRADX(N,J)=GRADX(N,J)-EPS_CONST(K,L)*FTERM*DISX   ! X COMPONENT OF THE GRADIENT
        GRADY(N,J)=GRADY(N,J)-EPS_CONST(K,L)*FTERM*DISY   ! Y COMPONENT OF THE GRADIENT
        GRADZ(N,J)=GRADZ(N,J)-EPS_CONST(K,L)*FTERM*DISZ   ! Z COMPONENT OF THE GRADIENT
     ENDDO
ENDDO

POT_ENER = POT_ENER + ENER1

END SUBROUTINE LENNARD_JONES


SUBROUTINE SPRING 
! SUBROUTINE TO COMPUTE THE HARMONIC OSCILLATOR POTENTIAL AND FORCE
! PEDRO OJEDA,  07/MAY/2011

USE PARAMETERS

REAL(DP)            :: FDUMMY1,FDUMMY2,FDUMMY3,FDUMMY4
REAL(DP)            :: ENER2
REAL(DP)            :: DISX,DISY,DISZ,DISPX,DISD,DISPY,DISPZ,DISPD

ENER2=0.0_DP

!HARMONIC POTENTIAL
FDUMMY3=2.0_DP*A_CONST

DO I=2,NUM_RES-1
    DISX=COORX(I)-COORX(I+1)                          
    DISY=COORY(I)-COORY(I+1)                          
    DISZ=COORZ(I)-COORZ(I+1)                           
    DISD=SQRT(DISX*DISX + DISY*DISY + DISZ*DISZ)        

    DISPX=COORX(I)-COORX(I-1)                          
    DISPY=COORY(I)-COORY(I-1)                          
    DISPZ=COORZ(I)-COORZ(I-1)                           
    DISPD=SQRT(DISPX*DISPX + DISPY*DISPY + DISPZ*DISPZ)       

    FDUMMY1=(DISD-R_CERO)
    FDUMMY2=FDUMMY1*FDUMMY1
    ENER2=ENER2+FDUMMY2
    FDUMMY4=(DISPD-R_CERO)
    GRADX(N,I)=GRADX(N,I)-FDUMMY3*DISX*FDUMMY1/DISD - FDUMMY3*DISPX*FDUMMY4/DISPD
    GRADY(N,I)=GRADY(N,I)-FDUMMY3*DISY*FDUMMY1/DISD - FDUMMY3*DISPY*FDUMMY4/DISPD
    GRADZ(N,I)=GRADZ(N,I)-FDUMMY3*DISZ*FDUMMY1/DISD - FDUMMY3*DISPZ*FDUMMY4/DISPD
ENDDO


    DISX=COORX(1)-COORX(2)                          
    DISY=COORY(1)-COORY(2)                          
    DISZ=COORZ(1)-COORZ(2)                           
    DISD=SQRT(DISX*DISX + DISY*DISY + DISZ*DISZ)       
    FDUMMY1=DISD-R_CERO
    FDUMMY2=FDUMMY1*FDUMMY1
    ENER2=ENER2+FDUMMY2
    GRADX(N,1)=GRADX(N,1)-FDUMMY3*DISX*FDUMMY1/DISD
    GRADY(N,1)=GRADY(N,1)-FDUMMY3*DISY*FDUMMY1/DISD
    GRADZ(N,1)=GRADZ(N,1)-FDUMMY3*DISZ*FDUMMY1/DISD


    DISX=COORX(NUM_RES)-COORX(NUM_RES-1)                          
    DISY=COORY(NUM_RES)-COORY(NUM_RES-1)                          
    DISZ=COORZ(NUM_RES)-COORZ(NUM_RES-1)                           
    DISD=SQRT(DISX*DISX + DISY*DISY + DISZ*DISZ)       
    FDUMMY1=DISD-R_CERO
    GRADX(N,NUM_RES)=GRADX(N,NUM_RES)-FDUMMY3*DISX*FDUMMY1/DISD
    GRADY(N,NUM_RES)=GRADY(N,NUM_RES)-FDUMMY3*DISY*FDUMMY1/DISD
    GRADZ(N,NUM_RES)=GRADZ(N,NUM_RES)-FDUMMY3*DISZ*FDUMMY1/DISD

POT_ENER = POT_ENER + A_CONST*ENER2

END SUBROUTINE SPRING


SUBROUTINE KINETIC 
! SUBROUTINE TO COMPUTE THE KINETIC ENERGY
! PEDRO OJEDA,  17/SEP/2021

USE PARAMETERS

REAL(DP)            :: ENER2

ENER2=0.0_DP

DO I=1,NUM_RES
      ENER2 = ENER2 + VELX(I)**2 + VELY(I)**2 + VELZ(I)**2 
ENDDO

      KIN_ENER = 0.5_DP*ENER2

END SUBROUTINE KINETIC


SUBROUTINE FORCES
! SUBROUTINE TO CALCULATE THE FORCES DEPENDING ON THE INTERACTIONS DESIRED
! PEDRO OJEDA,  07/MAY/2011

USE PARAMETERS 

  CALL INITIALIZE_GRAD
  CALL SPRING
  CALL LENNARD_JONES

END SUBROUTINE FORCES


SUBROUTINE UPDATE_VEL_VERLET_COOR
! SUBROUTINE TO UPDATE THE VELOCITIES BY MEANS OF THE VELOCITY VERLET ALGORITHM
! PEDRO OJEDA,  17/SEP/2021
USE PARAMETERS
INTEGER             :: P

DO P=1,NUM_RES
      COORX(P) = COORX(P) + DT*VELX(P) + 0.5_DP*DT2*GRADX(O,P) 
      COORY(P) = COORY(P) + DT*VELY(P) + 0.5_DP*DT2*GRADY(O,P) 
      COORZ(P) = COORZ(P) + DT*VELZ(P) + 0.5_DP*DT2*GRADZ(O,P)
ENDDO

END SUBROUTINE UPDATE_VEL_VERLET_COOR


SUBROUTINE UPDATE_VEL_VERLET_VEL
! SUBROUTINE TO UPDATE THE VELOCITIES BY MEANS OF THE VELOCITY VERLET ALGORITHM
! PEDRO OJEDA,  17/SEP/2021
USE PARAMETERS
INTEGER             :: P

DO P=1,NUM_RES
    VELX(P) = VELX(P) + DTP5 * ( GRADX(N,P) + GRADX(O,P) )
    VELY(P) = VELY(P) + DTP5 * ( GRADY(N,P) + GRADY(O,P) )
    VELZ(P) = VELZ(P) + DTP5 * ( GRADZ(N,P) + GRADZ(O,P) )
ENDDO

END SUBROUTINE UPDATE_VEL_VERLET_VEL


SUBROUTINE INITIALIZE
! SUBROUTINE TO INITIALIZE THE COORDINATES, VELOCITIES AND GRADIENT
! PEDRO OJEDA,  07/MAY/2011

USE PARAMETERS
USE RNG_UTILS

INTEGER             :: P

DO P=1,NUM_RES
    COORX(P)=  (P-15)*4.0_DP
    COORY(P)=  0.0_DP
    COORZ(P)=  0.0_DP

    VELX(P)=  1.0_DP*RANDN()
    VELY(P)=  1.0_DP*RANDN()
    VELZ(P)=  1.0_DP*RANDN()

    GRADX(N,P)=  0.0_DP
    GRADY(N,P)=  0.0_DP
    GRADZ(N,P)=  0.0_DP

    GRADX(O,P)=  0.0_DP
    GRADY(O,P)=  0.0_DP
    GRADZ(O,P)=  0.0_DP

    MASS(P)=  1.0_DP

ENDDO

POT_ENER = 0.0

END SUBROUTINE INITIALIZE


SUBROUTINE INITIALIZE_GRAD
! SUBROUTINE TO INITIALIZE THE GRADIENT AND POTENTIAL ENERGY
! PEDRO OJEDA,  07/MAY/2011

USE PARAMETERS

INTEGER             :: P

DO P=1,NUM_RES
    GRADX(N,P)=  0.0
    GRADY(N,P)=  0.0
    GRADZ(N,P)=  0.0
ENDDO

POT_ENER = 0.0_DP         
KIN_ENER = 0.0_DP           

END SUBROUTINE INITIALIZE_GRAD

