PROGRAM MOLECULAR_DYNAMICS
! MAIN PROGRAM TO RUN THE MOLECULAR DYNAMICS
! PEDRO OJEDA,  07/MAY/2011

USE PARAMETERS_MPI
USE RNG_UTILS_MPI
IMPLICIT NONE
INTEGER             :: NSTEP
INTEGER             :: P
INTEGER             :: TMP

REAL(DP) :: POT_TOTAL, KIN_TOTAL

CALL MPI_INIT(IERR)
CALL MPI_COMM_RANK(MPI_COMM_WORLD, MYRANK, IERR)
CALL MPI_COMM_SIZE(MPI_COMM_WORLD, NPROCS, IERR)

CALL SET_LOCAL_RANGE()
CALL INIT_RANDOM_SEED()
CALL INITIALIZE()
CALL EXCHANGE_COORDINATES()
CALL COMPUTE_FORCES(OLD)

IF (MYRANK == 0) THEN
   OPEN(88, FILE='KOORDINATEN_1T.xyz', STATUS='UNKNOWN')
ENDIF

T1 = MPI_WTIME()

!MAIN PART OF MOLECULAR DINAMICS
DO NSTEP=1,NSTEPS

     CALL UPDATE_COORDINATES()
     CALL EXCHANGE_COORDINATES()

     CALL COMPUTE_FORCES(NEW)
     CALL UPDATE_VELOCITIES()
     CALL KINETIC_ENERGY()

     IF (MOD(NSTEP, WRITE_FREQ) == 0) THEN
        CALL SUM_ENERGIES(POT_TOTAL, KIN_TOTAL)

        IF (MYRANK == 0) THEN
           WRITE(88,*) NUM_RES
           WRITE(88,*) ' '
           DO P = 1, NUM_RES
              WRITE(88,*) 'C', COOR(1,P), COOR(2,P), COOR(3,P)
           ENDDO
           WRITE(*,*) POT_TOTAL, KIN_TOTAL, POT_TOTAL + KIN_TOTAL
        ENDIF
     ENDIF
     TMP = OLD
     OLD = NEW
     NEW = TMP

ENDDO
T2 = MPI_WTIME()
IF (myrank == 0) THEN
    CLOSE(88)
    WRITE(*,*) 'PARALLEL TIME = ', T2 - T1, ' SECONDS'
ENDIF
CALL MPI_FINALIZE(IERR)

END PROGRAM MOLECULAR_DYNAMICS

SUBROUTINE COMPUTE_FORCES(SLOT)
  USE PARAMETERS_MPI
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: SLOT

  FORCE(:,SLOT,ISTART:IEND) = 0.0_DP
  POT_ENER = 0.0_DP
  KIN_ENER = 0.0_DP

  CALL SPRING_FORCE(SLOT)
  CALL LENNARD_JONES_FORCE(SLOT)
END SUBROUTINE COMPUTE_FORCES

SUBROUTINE LENNARD_JONES_FORCE(SLOT)
  USE PARAMETERS_MPI
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: SLOT
  INTEGER :: I, J
  REAL(DP) :: RIJ(3), R2
  REAL(DP) :: SR2, SR4, SR6, SR12
  REAL(DP) :: FTERM, EIJ

  DO I = ISTART, IEND
     DO J = 1, NUM_RES

        IF (J == I) CYCLE
        IF (ABS(J-I) <= 1) CYCLE

        RIJ = COOR(:,I) - COOR(:,J)
        R2 = SUM(RIJ*RIJ)

        SR2  = SIGMA_CONST*SIGMA_CONST/R2
        SR4  = SR2*SR2
        SR6  = SR4*SR2
        SR12 = SR6*SR6

        EIJ = EPS_CONST*(SR12 - SR6)
        FTERM = EPS_CONST*(12.0_DP*SR12 - 6.0_DP*SR6)/R2

        FORCE(:,SLOT,I) = FORCE(:,SLOT,I) + FTERM*RIJ

        IF (J > I+1) POT_ENER = POT_ENER + EIJ

     ENDDO
  ENDDO

END SUBROUTINE LENNARD_JONES_FORCE

SUBROUTINE SPRING_FORCE(SLOT)
  USE PARAMETERS_MPI
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: SLOT
  INTEGER :: I
  REAL(DP) :: RIJ(3), R, DR, FIJ(3)

  DO I = ISTART, IEND

     IF (I < NUM_RES) THEN
        RIJ = COOR(:,I) - COOR(:,I+1)
        R = SQRT(SUM(RIJ*RIJ))
        DR = R - R_CERO

        FIJ = -2.0_DP*A_CONST*DR*RIJ/R
        FORCE(:,SLOT,I) = FORCE(:,SLOT,I) + FIJ

        POT_ENER = POT_ENER + A_CONST*DR*DR
     ENDIF

     IF (I > 1) THEN
        RIJ = COOR(:,I) - COOR(:,I-1)
        R = SQRT(SUM(RIJ*RIJ))
        DR = R - R_CERO

        FIJ = -2.0_DP*A_CONST*DR*RIJ/R
        FORCE(:,SLOT,I) = FORCE(:,SLOT,I) + FIJ
     ENDIF

  ENDDO

END SUBROUTINE SPRING_FORCE

SUBROUTINE UPDATE_COORDINATES()
  USE PARAMETERS_MPI
  IMPLICIT NONE

  INTEGER :: P

  DO P = ISTART, IEND
     COOR(:,P) = COOR(:,P) + DT*VEL(:,P) + 0.5_DP*DT2*FORCE(:,OLD,P)/MASS(P)
  ENDDO
END SUBROUTINE UPDATE_COORDINATES

SUBROUTINE UPDATE_VELOCITIES()
  USE PARAMETERS_MPI
  IMPLICIT NONE

  INTEGER :: P

  DO P = ISTART, IEND
     VEL(:,P) = VEL(:,P) + DTP5*(FORCE(:,NEW,P) + FORCE(:,OLD,P))/MASS(P)
  ENDDO
END SUBROUTINE UPDATE_VELOCITIES

SUBROUTINE KINETIC_ENERGY()
  USE PARAMETERS_MPI
  IMPLICIT NONE

  INTEGER :: P

  KIN_ENER = 0.0_DP

  DO P = ISTART, IEND
     KIN_ENER = KIN_ENER + MASS(P)*SUM(VEL(:,P)*VEL(:,P))
  ENDDO

  KIN_ENER = 0.5_DP*KIN_ENER
END SUBROUTINE KINETIC_ENERGY

SUBROUTINE INITIALIZE()
  USE PARAMETERS_MPI
  USE RNG_UTILS_MPI
  IMPLICIT NONE

  INTEGER :: P

  COOR  = 0.0_DP
  VEL   = 0.0_DP
  FORCE = 0.0_DP
  MASS  = 1.0_DP

  DO P = ISTART, IEND
     COOR(:,P) = [ (P-15)*4.0_DP, 0.0_DP, 0.0_DP ]
     VEL(:,P)  = [ RANDN(), RANDN(), RANDN() ]
  ENDDO

  POT_ENER = 0.0_DP
  KIN_ENER = 0.0_DP
END SUBROUTINE INITIALIZE

SUBROUTINE SET_LOCAL_RANGE()
  USE PARAMETERS_MPI
  IMPLICIT NONE

  INTEGER :: BASE, REM

  BASE = NUM_RES / NPROCS
  REM  = MOD(NUM_RES, NPROCS)

  IF (MYRANK < REM) THEN
     NLOCAL = BASE + 1
     ISTART = MYRANK*NLOCAL + 1
  ELSE
     NLOCAL = BASE
     ISTART = REM*(BASE+1) + (MYRANK-REM)*BASE + 1
  ENDIF

  IEND = ISTART + NLOCAL - 1
END SUBROUTINE SET_LOCAL_RANGE


SUBROUTINE EXCHANGE_COORDINATES()
  USE PARAMETERS_MPI
  IMPLICIT NONE

  INTEGER :: R, BASE, REM
  INTEGER :: NLOC_R, START_R
  INTEGER, ALLOCATABLE :: COUNTS(:), DISPLS(:)

  ALLOCATE(COUNTS(NPROCS), DISPLS(NPROCS))

  BASE = NUM_RES / NPROCS
  REM  = MOD(NUM_RES, NPROCS)

  DO R = 0, NPROCS-1

     IF (R < REM) THEN
        NLOC_R  = BASE + 1
        START_R = R*NLOC_R + 1
     ELSE
        NLOC_R  = BASE
        START_R = REM*(BASE+1) + (R-REM)*BASE + 1
     ENDIF

     COUNTS(R+1) = 3*NLOC_R
     DISPLS(R+1) = 3*(START_R - 1)

  ENDDO

  CALL MPI_ALLGATHERV(COOR(1,ISTART), 3*NLOCAL, MPI_DOUBLE_PRECISION, &
                      COOR, COUNTS, DISPLS, MPI_DOUBLE_PRECISION, &
                      MPI_COMM_WORLD, IERR)

  DEALLOCATE(COUNTS, DISPLS)

END SUBROUTINE EXCHANGE_COORDINATES

SUBROUTINE SUM_ENERGIES(POT_TOTAL, KIN_TOTAL)
  USE PARAMETERS_MPI
  IMPLICIT NONE

  REAL(DP), INTENT(OUT) :: POT_TOTAL, KIN_TOTAL
  REAL(DP) :: LOCAL_BUFFER(2)
  REAL(DP) :: GLOBAL_BUFFER(2)

  LOCAL_BUFFER(1) = POT_ENER
  LOCAL_BUFFER(2) = KIN_ENER

  CALL MPI_ALLREDUCE(LOCAL_BUFFER, GLOBAL_BUFFER, 2, &
                     MPI_DOUBLE_PRECISION, MPI_SUM, &
                     MPI_COMM_WORLD, IERR)

  POT_TOTAL = GLOBAL_BUFFER(1)
  KIN_TOTAL = GLOBAL_BUFFER(2)

END SUBROUTINE SUM_ENERGIES


