PROGRAM MOLECULAR_DYNAMICS
! MAIN PROGRAM TO RUN THE MOLECULAR DYNAMICS
! PEDRO OJEDA,  07/MAY/2011

USE PARAMETERS_SERIAL
USE RNG_UTILS_SERIAL
IMPLICIT NONE
INTEGER             :: NSTEP
INTEGER             :: P
INTEGER             :: TMP


CALL INIT_RANDOM_SEED()
CALL INITIALIZE()
CALL COMPUTE_FORCES()

OPEN(88,FILE='KOORDINATEN_1T.xyz',STATUS='UNKNOWN')

CALL CPU_TIME(T1)

!MAIN PART OF MOLECULAR DINAMICS
DO NSTEP=1,NSTEPS

     CALL UPDATE_COORDINATES()
     CALL COMPUTE_FORCES()
     CALL UPDATE_VELOCITIES()
     CALL KINETIC_ENERGY()

     IF (MOD(NSTEP, WRITE_FREQ) == 0) THEN
        WRITE(88,*) NUM_RES
        WRITE(88,*) ' '
        DO P = 1, NUM_RES
           WRITE(88,*) 'C', COOR(1,P), COOR(2,P), COOR(3,P)
        ENDDO
        WRITE(*,*) POT_ENER, KIN_ENER, POT_ENER + KIN_ENER
     ENDIF
     TMP = OLD
     OLD = NEW
     NEW = TMP

ENDDO
CALL CPU_TIME(T2)
WRITE(*,*) 'SERIAL TIME = ', T2 - T1, ' SECONDS'
CLOSE(88)

END PROGRAM MOLECULAR_DYNAMICS

SUBROUTINE COMPUTE_FORCES()
  USE PARAMETERS_SERIAL
  IMPLICIT NONE

  FORCE(:,NEW,:) = 0.0_DP
  POT_ENER = 0.0_DP
  KIN_ENER = 0.0_DP

  CALL SPRING_FORCE()
  CALL LENNARD_JONES_FORCE()
END SUBROUTINE COMPUTE_FORCES

SUBROUTINE LENNARD_JONES_FORCE()
  USE PARAMETERS_SERIAL
  IMPLICIT NONE

  INTEGER :: I, J
  REAL(DP) :: RIJ(3), R2
  REAL(DP) :: SR2, SR4, SR6, SR12
  REAL(DP) :: FTERM, EIJ

  DO I = 1, NUM_RES-2
     DO J = I+2, NUM_RES

        RIJ = COOR(:,I) - COOR(:,J)
        R2 = SUM(RIJ*RIJ)

        SR2  = SIGMA_CONST*SIGMA_CONST/R2
        SR4  = SR2*SR2
        SR6  = SR4*SR2
        SR12 = SR6*SR6

        EIJ = EPS_CONST*(SR12 - SR6)
        FTERM = EPS_CONST*(12.0_DP*SR12 - 6.0_DP*SR6)/R2

        POT_ENER = POT_ENER + EIJ

        FORCE(:,NEW,I) = FORCE(:,NEW,I) + FTERM*RIJ
        FORCE(:,NEW,J) = FORCE(:,NEW,J) - FTERM*RIJ

     ENDDO
  ENDDO

END SUBROUTINE LENNARD_JONES_FORCE

SUBROUTINE SPRING_FORCE()
  USE PARAMETERS_SERIAL
  IMPLICIT NONE

  INTEGER :: I
  REAL(DP) :: RIJ(3), R, DR, FIJ(3)

  DO I = 1, NUM_RES-1

     RIJ = COOR(:,I) - COOR(:,I+1)
     R = SQRT(SUM(RIJ*RIJ))
     DR = R - R_CERO

     POT_ENER = POT_ENER + A_CONST*DR*DR

     FIJ = -2.0_DP*A_CONST*DR*RIJ/R

     FORCE(:,NEW,I)   = FORCE(:,NEW,I)   + FIJ
     FORCE(:,NEW,I+1) = FORCE(:,NEW,I+1) - FIJ

  ENDDO

END SUBROUTINE SPRING_FORCE

SUBROUTINE UPDATE_COORDINATES()
  USE PARAMETERS_SERIAL
  IMPLICIT NONE

  INTEGER :: P

  DO P = 1, NUM_RES
     COOR(:,P) = COOR(:,P) + DT*VEL(:,P) + 0.5_DP*DT2*FORCE(:,OLD,P)/MASS(P)
  ENDDO
END SUBROUTINE UPDATE_COORDINATES

SUBROUTINE UPDATE_VELOCITIES()
  USE PARAMETERS_SERIAL
  IMPLICIT NONE

  INTEGER :: P

  DO P = 1, NUM_RES
     VEL(:,P) = VEL(:,P) + DTP5*(FORCE(:,NEW,P) + FORCE(:,OLD,P))/MASS(P)
  ENDDO
END SUBROUTINE UPDATE_VELOCITIES

SUBROUTINE KINETIC_ENERGY()
  USE PARAMETERS_SERIAL
  IMPLICIT NONE

  INTEGER :: P

  KIN_ENER = 0.0_DP

  DO P = 1, NUM_RES
     KIN_ENER = KIN_ENER + MASS(P)*SUM(VEL(:,P)*VEL(:,P))
  ENDDO

  KIN_ENER = 0.5_DP*KIN_ENER
END SUBROUTINE KINETIC_ENERGY

SUBROUTINE INITIALIZE()
  USE PARAMETERS_SERIAL
  USE RNG_UTILS_SERIAL
  IMPLICIT NONE

  INTEGER :: P

  DO P = 1, NUM_RES
     COOR(:,P) = [ (P-15)*4.0_DP, 0.0_DP, 0.0_DP ]
     VEL(:,P)  = [ RANDN(), RANDN(), RANDN() ]
     FORCE(:,:,P) = 0.0_DP
     MASS(P) = 1.0_DP
  ENDDO

  POT_ENER = 0.0_DP
  KIN_ENER = 0.0_DP
END SUBROUTINE INITIALIZE


