MODULE PARAMETERS_MPI
! MODULE WITH THE PARAMETERS NEEDED IN THE SIMULATION
! PEDRO OJEDA,  07/MAY/2011
   USE MPI
   IMPLICIT NONE
   INTEGER, PARAMETER  :: NUM_RES=1000                     !NUMBER OF AMINOACIDS IN EACH SEQUENCE
   INTEGER, PARAMETER  :: DP = SELECTED_REAL_KIND(12, 60)
   INTEGER, PARAMETER  :: NSTEPS=10000                     !TIME OF SIMULATION
   INTEGER, PARAMETER  :: WRITE_FREQ = 1000                ! FREQUENCY OF WRITING FILES
   REAL(DP),PARAMETER  :: PI=3.141592653589793_DP          !PI CONSTANT
   REAL(DP),PARAMETER  :: DT=0.001_DP                      !TIME STEP
   REAL(DP)            :: DT2=DT*DT                        !TIME STEP SQUARED
   REAL(DP)            :: DTP5=0.5_DP*DT                   !TIME STEP HALFED
   REAL(DP),PARAMETER  :: EPS_CONST = 40.0_DP              !ARRAY FOR EPSILON
   REAL(DP),PARAMETER  :: SIGMA_CONST = 6.5_DP             !ARRAY OF SIGMA
   REAL(DP),PARAMETER  :: R_CERO=3.8_DP                    !SPRING EQUILIBRIUM SEPARATION
   REAL(DP),PARAMETER  :: A_CONST=50.0_DP                  !SPRING CONSTANT
   REAL(DP)            :: POT_ENER                         !POTENTIAL ENERGY
   REAL(DP)            :: KIN_ENER                         !KINETIC ENERGY
   REAL(DP)            :: T1,T2                            !TIMING VARIABLES
   
   INTEGER             :: OLD = 1, NEW = 2                 !INDICES FOR OLD AND NEW CONFIGURATIONS
   
   ! PARTICLE DATA (STRUCTURE OF ARRAYS)
   REAL(DP), SAVE :: COOR(3,NUM_RES)                       !COORDINATES 3*NUM_RES
   REAL(DP), SAVE :: VEL(3,NUM_RES)                        !VELOCITIES 
   REAL(DP), SAVE :: FORCE(3,2,NUM_RES)                    !FORCES
   REAL(DP), SAVE :: MASS(NUM_RES)                         !MASS

   ! MPI RELATED VARIABLES
   INTEGER :: MYRANK, NPROCS, IERR
   INTEGER :: ISTART, IEND, NLOCAL
END MODULE PARAMETERS_MPI

MODULE RNG_UTILS_MPI
  USE PARAMETERS_MPI
  IMPLICIT NONE
CONTAINS

  SUBROUTINE INIT_RANDOM_SEED()
    INTEGER :: i, n, clock
    INTEGER, ALLOCATABLE :: seed(:)

    CALL RANDOM_SEED(SIZE=n)
    ALLOCATE(seed(n))

    CALL SYSTEM_CLOCK(COUNT=clock)

    DO i = 1, n
       SEED(I) = CLOCK + 37*I + 104729*MYRANK
    ENDDO

    CALL RANDOM_SEED(PUT=SEED)
    DEALLOCATE(SEED)
  END SUBROUTINE INIT_RANDOM_SEED


  FUNCTION RANDN() RESULT(Z)
    REAL(DP) :: z
    REAL(DP) :: u1, u2

    CALL RANDOM_NUMBER(u1)
    CALL RANDOM_NUMBER(u2)

    IF (U1 <= 1.0E-12_DP) U1 = 1.0E-12_DP

    z = SQRT(-2.0_DP*LOG(u1)) * COS(2.0_DP*PI*u2)
  END FUNCTION RANDN

END MODULE RNG_UTILS_MPI
